In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.full(5,10)


array([10, 10, 10, 10, 10])

In [6]:
a=np.array([1,2,3,4,5])

In [7]:
a

array([1, 2, 3, 4, 5])

In [10]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [13]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n=np.array([[1,2,3],[3,4,5],[6,7,8]])

In [15]:
n

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
n[0,2]=67

In [18]:
n

array([[ 1,  2, 67],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [19]:
np.random.rand(5,2)

array([[0.07391027, 0.33047133],
       [0.8915442 , 0.60812933],
       [0.27623117, 0.7351319 ],
       [0.07631981, 0.19366193],
       [0.23468517, 0.10203434]])

In [20]:
np.random.seed(2)

In [21]:
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [23]:
np.random.seed(2)

In [24]:
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [25]:
np.random.seed(2)

In [26]:
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])